updating build update

diff --git a/build-update-hld.yaml b/build-update-hld.yaml
--- a/build-update-hld.yaml
+++ b/build-update-hld.yaml
@@ -1,3 +1,4 @@
+# GENERATED WITH SPK VERSION 0.5.8
 trigger:
   branches:
     include:
@@ -14,6 +15,9 @@ stages:
         pool:
           vmImage: ubuntu-latest
         steps:
+          - task: HelmInstaller@1
+            inputs:
+              helmVersionToInstall: 2.16.3
           - script: |-
               set -e
               echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
@@ -21,28 +25,37 @@ stages:
             displayName: Azure Login
           - script: |-
               set -e
+              # Download build.sh
+              curl $BEDROCK_BUILD_SCRIPT > build.sh
+              chmod +x ./build.sh
+            displayName: Download bedrock bash scripts
+            env:
+              BEDROCK_BUILD_SCRIPT: $(BUILD_SCRIPT_URL)
+          - script: |-
+              set -e
               export BUILD_REPO_NAME=$(echo $(Build.Repository.Name)-fabrikam.acme.frontend | tr '[:upper:]' '[:lower:]')
-              tag_name="$BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)"
+              tag_name="$BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)"
               commitId=$(Build.SourceVersion)
               commitId=$(echo "${commitId:0:7}")
               service=$(Build.Repository.Name)
               service=${service##*/}
-              echo "Downloading SPK"
-              curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
-              chmod +x build.sh
+              url=$(git remote --verbose | grep origin | grep fetch | cut -f2 | cut -d' ' -f1)
+              repourl=${url##*@}
               . ./build.sh --source-only
               get_spk_version
               download_spk
-              ./spk/spk deployment create -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p1 $(Build.BuildId) --image-tag $tag_name --commit-id $commitId --service $service
+              ./spk/spk deployment create -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p1 $(Build.BuildId) --image-tag $tag_name --commit-id $commitId --service $service --repository $repourl
             displayName: 'If configured, update Spektate storage with build pipeline'
             condition: 'and(ne(variables[''INTROSPECTION_ACCOUNT_NAME''], ''''), ne(variables[''INTROSPECTION_ACCOUNT_KEY''], ''''),ne(variables[''INTROSPECTION_TABLE_NAME''], ''''),ne(variables[''INTROSPECTION_PARTITION_KEY''], ''''))'
           - script: |-
               set -e
               export BUILD_REPO_NAME=$(echo $(Build.Repository.Name)-fabrikam.acme.frontend | tr '[:upper:]' '[:lower:]')
-              echo "Image Name: $BUILD_REPO_NAME"
+              export IMAGE_TAG=$(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)
+              export IMAGE_NAME=$BUILD_REPO_NAME:$IMAGE_TAG
+              echo "Image Name: $IMAGE_NAME"
               cd ./services/fabrikam.acme.frontend
-              echo "az acr build -r $(ACR_NAME) --image $BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber) --file ../Dockerfiles/some-other-Dockerfile ."
-              az acr build -r $(ACR_NAME) --image $BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber) .
+              echo "az acr build -r $(ACR_NAME) --image $IMAGE_NAME ."
+              az acr build -r $(ACR_NAME) --image $IMAGE_NAME .
             displayName: ACR Build and Publish
   - stage: hld_update
     dependsOn: build
@@ -52,6 +65,9 @@ stages:
         pool:
           vmImage: ubuntu-latest
         steps:
+          - task: HelmInstaller@1
+            inputs:
+              helmVersionToInstall: 2.16.3
           - script: |-
               set -e
               # Download build.sh
@@ -64,8 +80,8 @@ stages:
               set -e
               export SERVICE_NAME_LOWER=$(echo fabrikam.acme.frontend | tr '[:upper:]' '[:lower:]')
               export BUILD_REPO_NAME=$(echo $(Build.Repository.Name)-fabrikam.acme.frontend | tr '[:upper:]' '[:lower:]')
-              export BRANCH_NAME=DEPLOY/$BUILD_REPO_NAME-$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)
-              export FAB_SAFE_SERVICE_NAME=$(SERVICE_NAME_LOWER | tr . - | tr / -)
+              export BRANCH_NAME=DEPLOY/$BUILD_REPO_NAME-$(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)
+              export FAB_SAFE_SERVICE_NAME=$(echo $SERVICE_NAME_LOWER | tr . - | tr / -)
               # --- From https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/release.sh
               . build.sh --source-only
 
@@ -84,19 +100,23 @@ stages:
 
               # Update HLD
               git checkout -b "$BRANCH_NAME"
-              ../fab/fab set --subcomponent $(Build.Repository.Name).$FAB_SAFE_SERVICE_NAME.$(echo $(Build.SourceBranchName) | tr / - | tr . -).chart image.tag=$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)
-              echo "GIT STATUS"
-              git status
-              echo "GIT ADD (git add -A)"
-              git add -A
+              export BUILD_REPO_NAME=$(echo $(Build.Repository.Name)-fabrikam.acme.frontend | tr '[:upper:]' '[:lower:]')
+              export IMAGE_TAG=$(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)
+              export IMAGE_NAME=$BUILD_REPO_NAME:$IMAGE_TAG
+              echo "Image Name: $IMAGE_NAME"
+              export IMAGE_REPO=$(echo $(ACR_NAME).azurecr.io | tr '[:upper:]' '[:lower:]')
+              echo "Image Repository: $IMAGE_REPO"
+              cd $(Build.Repository.Name)/$FAB_SAFE_SERVICE_NAME/$(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )
+              echo "FAB SET"
+              fab set --subcomponent chart image.tag=$IMAGE_TAG image.repository=$IMAGE_REPO/$BUILD_REPO_NAME
 
               # Set git identity
               git config user.email "admin@azuredevops.com"
               git config user.name "Automated Account"
 
               # Commit changes
-              echo "GIT COMMIT"
-              git commit -m "Updating $SERVICE_NAME_LOWER image tag to $(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)."
+              echo "GIT ADD and COMMIT -- Will throw error if there is nothing to commit."
+              git_commit_if_changes "Updating $SERVICE_NAME_LOWER image tag to $(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)." 1 unusedVar
 
               # Git Push
               git_push
@@ -105,24 +125,21 @@ stages:
               echo 'az extension add --name azure-devops'
               az extension add --name azure-devops
 
-              echo 'az repos pr create --description "Updating $SERVICE_NAME_LOWER to $(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)." "PR created by: $(Build.DefinitionName) with buildId: $(Build.BuildId) and buildNumber: $(Build.BuildNumber)"'
-              response=$(az repos pr create --description "Updating $SERVICE_NAME_LOWER to $(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)." "PR created by: $(Build.DefinitionName) with buildId: $(Build.BuildId) and buildNumber: $(Build.BuildNumber)")
+              echo 'az repos pr create --description "Updating $SERVICE_NAME_LOWER to $(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)." "PR created by: $(Build.DefinitionName) with buildId: $(Build.BuildId) and buildNumber: $(Build.BuildNumber)"'
+              response=$(az repos pr create --description "Updating $SERVICE_NAME_LOWER to $(echo $(Build.SourceBranchName) | tr / - | tr . - | tr _ - )-$(Build.BuildNumber)." "PR created by: $(Build.DefinitionName) with buildId: $(Build.BuildId) and buildNumber: $(Build.BuildNumber)")
               pr_id=$(echo $response | jq -r '.pullRequestId')
-
 
               # Update introspection storage with this information, if applicable
               if [ -z "$(INTROSPECTION_ACCOUNT_NAME)" -o -z "$(INTROSPECTION_ACCOUNT_KEY)" -o -z "$(INTROSPECTION_TABLE_NAME)" -o -z "$(INTROSPECTION_PARTITION_KEY)" ]; then
               echo "Introspection variables are not defined. Skipping..."
               else
               latest_commit=$(git rev-parse --short HEAD)
-              tag_name="$BUILD_REPO_NAME:$(echo $(Build.SourceBranchName) | tr / - | tr . -)-$(Build.BuildNumber)"
-              echo "Downloading SPK"
-              curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
-              chmod +x build.sh
-              . ./build.sh --source-only
+              tag_name="$BUILD_REPO_NAME:$(Build.SourceBranchName)-$(Build.BuildNumber)"
+              url=$(git remote --verbose | grep origin | grep fetch | cut -f2 | cut -d' ' -f1)
+              repourl=${url##*@}
               get_spk_version
               download_spk
-              ./spk/spk deployment create  -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p2 $(Build.BuildId) --hld-commit-id $latest_commit --env $BRANCH_NAME --image-tag $tag_name --pr $pr_id
+              ./spk/spk deployment create  -n $(INTROSPECTION_ACCOUNT_NAME) -k $(INTROSPECTION_ACCOUNT_KEY) -t $(INTROSPECTION_TABLE_NAME) -p $(INTROSPECTION_PARTITION_KEY) --p2 $(Build.BuildId) --hld-commit-id $latest_commit --env $BRANCH_NAME --image-tag $tag_name --pr $pr_id --repository $repourl
               fi
             displayName: 'Download Fabrikate, Update HLD, Push changes, Open PR, and if configured, push to Spektate storage'
             env:
